
train_file:  '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/en/train.jsonl' #'/remote-home/zjli/CVLM/datasets/GQA/questions/train_all_questions/train_all_questions_*.json'
val_file: 
  en: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/en/dev.jsonl'
  ar: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/en/dev-ar_gmt.jsonl'
  es: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/en/dev-es_gmt.jsonl'
  fr: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/en/dev-fr_gmt.jsonl'
  ru: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/en/dev-ru_gmt.jsonl'               
test_file: 
  en: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/en/test.jsonl'
  ar: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/ar/test.jsonl'
  es: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/es/test.jsonl'
  fr: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/fr/test.jsonl'
  ru: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/ru/test.jsonl'
translate_test_file:
  en: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations/en/test.jsonl'
  ar: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations_machine-translate/ar/test.jsonl'
  es: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations_machine-translate/es/test.jsonl'
  fr: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations_machine-translate/fr/test.jsonl'
  ru: '/remote-home/zjli/CVLM/datasets/iglue/datasets/XVNLI/annotations_machine-translate/ru/test.jsonl'


image_root: 
  remote: '/remote-home/zjli/flickr30k/flickr30k-images/' #flickr30k-images/
  local: '/root/pretrain_datasets/flickr30k/'

bert_config: 'albef/configs/config_xlm-r.json'

image_res: 384
batch_size_train: 32
batch_size_test: 64

vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128
text_encoder: 'bert-base-uncased'
model_type: 'classification' # or generation
answer_num: 1853
cls_head: {head_type: 'linear', class_num: 3}
freeze_module: ['txt_encoder', 'vis_encoder', 'embedding']

alpha: 0.4
distill: True
warm_up: True

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02} 
schedular: {sched: cosine, lr: 1e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}