
train_file:  '/remote-home/zjli/CVLM/datasets/GQA/questions/train_balanced_questions.json' #'/remote-home/zjli/CVLM/datasets/GQA/questions/train_all_questions/train_all_questions_*.json'
val_file: 
  en: '/remote-home/zjli/CVLM/datasets/GQA/questions/val_balanced_questions.json'
  zh: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/few_shot/zh/dev.json'
  bn: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/few_shot/bn/dev.json'   
  de: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/few_shot/de/dev.json'   
  id: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/few_shot/id/dev.json'   
  ko: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/few_shot/ko/dev.json'   
  pt: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/few_shot/pt/dev.json'
  ru: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/few_shot/ru/dev.json'   
test_file: 
  zh: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/zero_shot/testdev_balanced_questions_zh.json'
  en: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/zero_shot/testdev_balanced_questions_en.json'
  bn: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/zero_shot/testdev_balanced_questions_bn.json'
  de: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/zero_shot/testdev_balanced_questions_de.json'
  ko: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/zero_shot/testdev_balanced_questions_ko.json'
  pt: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/zero_shot/testdev_balanced_questions_pt.json'
  ru: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/zero_shot/testdev_balanced_questions_ru.json'
  id: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/zero_shot/testdev_balanced_questions_id.json'
translate_test_file:
  zh: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xGQA/annotations_machine-translate/zero_shot/testdev_balanced_questions_zh.json'
  en: '/remote-home/zjli/CVLM/datasets/GQA/xGQA-master/data/zero_shot/testdev_balanced_questions_en.json'
  bn: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xGQA/annotations_machine-translate/zero_shot/testdev_balanced_questions_bn.json'
  de: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xGQA/annotations_machine-translate/zero_shot/testdev_balanced_questions_de.json'
  ko: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xGQA/annotations_machine-translate/zero_shot/testdev_balanced_questions_ko.json'
  pt: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xGQA/annotations_machine-translate/zero_shot/testdev_balanced_questions_pt.json'
  ru: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xGQA/annotations_machine-translate/zero_shot/testdev_balanced_questions_ru.json'
  id: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xGQA/annotations_machine-translate/zero_shot/testdev_balanced_questions_id.json'

image_root: 
  remote: '/remote-home/zjli/CVLM/datasets/GQA/images/' #flickr30k-images/
  local: '/root/pretrain_datasets/GQA/'

bert_config: 'albef/configs/config_xlm-r.json'

image_res: 384
batch_size_train: 32
batch_size_test: 64

vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128
text_encoder: 'bert-base-uncased'
model_type: 'classification' # or generation
answer_num: 1853
freeze_module: ['txt_encoder', 'vis_encoder', 'embedding']

alpha: 0.4
distill: True
warm_up: True

optimizer: {opt: adamW, lr: 3e-5, weight_decay: 0.02} 
schedular: {sched: cosine, lr: 1e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}