
train_file:  '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations/train_ann.jsonl' #'/remote-home/zjli/CVLM/datasets/GQA/questions/train_all_questions/train_all_questions_*.json'
val_file: 
  en: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations/valid_ann.jsonl'
  de: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations_machine-translate/valid-de_gmt.jsonl'
  es: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations_machine-translate/valid-es_gmt.jsonl'
  id: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations_machine-translate/valid-id_gmt.jsonl'
  ja: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations_machine-translate/valid-ja_gmt.jsonl'
  ru: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations_machine-translate/valid-ru_gmt.jsonl'
  tr: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations_machine-translate/valid-tr_gmt.jsonl'
  zh: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations_machine-translate/valid-zh_gmt.jsonl'            
test_file: 
  en: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations/test_ann.jsonl'
  de: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations/de/test.jsonl'
  es: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations/es/test.jsonl'
  id: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations/id/test.jsonl'
  ja: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations/ja/test.jsonl'
  ru: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations/ru/test.jsonl'
  tr: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations/tr/test.jsonl'
  zh: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations/zh/test.jsonl'
translate_test_file:
  en: '/remote-home/zjli/CVLM/datasets/iglue/datasets/flickr30k/annotations/test_ann.jsonl'
  de: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations_machine-translate/de/test_gmt.jsonl'
  es: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations_machine-translate/es/test_gmt.jsonl'
  id: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations_machine-translate/id/test_gmt.jsonl'
  ja: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations_machine-translate/ja/test_gmt.jsonl'
  ru: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations_machine-translate/ru/test_gmt.jsonl'
  tr: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations_machine-translate/tr/test_gmt.jsonl'
  zh: '/remote-home/zjli/CVLM/datasets/iglue/datasets/xFlickrCO/annotations_machine-translate/zh/test_gmt.jsonl'


image_root: 
  remote:
    flickr: '/remote-home/zjli/flickr30k/flickr30k-images/' #flickr30k-images/
    coco: '/remote-home/share/VQA/Images/'
  local:
    flickr: '/root/pretrain_datasets/flickr30k/' #flickr30k-images/
    coco: '/root/pretrain_datasets/coco2015/'

bert_config: 'albef/configs/config_xlm-r.json'

image_res: 384
batch_size_train: 32
batch_size_test: 64

vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128
text_encoder: 'bert-base-uncased'
model_type: 'classification' # or generation
answer_num: 1853
cls_head: {head_type: 'linear', class_num: 3}
freeze_module: []

alpha: 0.4
distill: True
warm_up: True

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02} 
schedular: {sched: cosine, lr: 1e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}